/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnswerDTO } from './AnswerDTO';
import {
    AnswerDTOFromJSON,
    AnswerDTOFromJSONTyped,
    AnswerDTOToJSON,
} from './AnswerDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface AnswerDTORequestResponse
 */
export interface AnswerDTORequestResponse {
    /**
     * 
     * @type {AnswerDTO}
     * @memberof AnswerDTORequestResponse
     */
    response?: AnswerDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof AnswerDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the AnswerDTORequestResponse interface.
 */
export function instanceOfAnswerDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnswerDTORequestResponseFromJSON(json: any): AnswerDTORequestResponse {
    return AnswerDTORequestResponseFromJSONTyped(json, false);
}

export function AnswerDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : AnswerDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function AnswerDTORequestResponseToJSON(value?: AnswerDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': AnswerDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

