/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserGetDTO } from './UserGetDTO';
import {
    UserGetDTOFromJSON,
    UserGetDTOFromJSONTyped,
    UserGetDTOToJSON,
} from './UserGetDTO';

/**
 * 
 * @export
 * @interface AnswerGetDTO
 */
export interface AnswerGetDTO {
    /**
     * 
     * @type {string}
     * @memberof AnswerGetDTO
     */
    description?: string | null;
    /**
     * 
     * @type {UserGetDTO}
     * @memberof AnswerGetDTO
     */
    respondingUser?: UserGetDTO;
    /**
     * 
     * @type {Date}
     * @memberof AnswerGetDTO
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the AnswerGetDTO interface.
 */
export function instanceOfAnswerGetDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnswerGetDTOFromJSON(json: any): AnswerGetDTO {
    return AnswerGetDTOFromJSONTyped(json, false);
}

export function AnswerGetDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerGetDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'respondingUser': !exists(json, 'respondingUser') ? undefined : UserGetDTOFromJSON(json['respondingUser']),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function AnswerGetDTOToJSON(value?: AnswerGetDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'respondingUser': UserGetDTOToJSON(value.respondingUser),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

