/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnswerUpdateDTO
 */
export interface AnswerUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof AnswerUpdateDTO
     */
    answerId?: string;
    /**
     * 
     * @type {string}
     * @memberof AnswerUpdateDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the AnswerUpdateDTO interface.
 */
export function instanceOfAnswerUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnswerUpdateDTOFromJSON(json: any): AnswerUpdateDTO {
    return AnswerUpdateDTOFromJSONTyped(json, false);
}

export function AnswerUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'answerId': !exists(json, 'answerId') ? undefined : json['answerId'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function AnswerUpdateDTOToJSON(value?: AnswerUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'answerId': value.answerId,
        'description': value.description,
    };
}

