/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackUpdateDTO
 */
export interface FeedbackUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateDTO
     */
    feedbackId?: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackUpdateDTO
     */
    rating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateDTO
     */
    frequentedSection?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackUpdateDTO
     */
    suggestion?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FeedbackUpdateDTO
     */
    responseWanted?: number | null;
}

/**
 * Check if a given object implements the FeedbackUpdateDTO interface.
 */
export function instanceOfFeedbackUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackUpdateDTOFromJSON(json: any): FeedbackUpdateDTO {
    return FeedbackUpdateDTOFromJSONTyped(json, false);
}

export function FeedbackUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'feedbackId': !exists(json, 'feedbackId') ? undefined : json['feedbackId'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'frequentedSection': !exists(json, 'frequentedSection') ? undefined : json['frequentedSection'],
        'suggestion': !exists(json, 'suggestion') ? undefined : json['suggestion'],
        'responseWanted': !exists(json, 'responseWanted') ? undefined : json['responseWanted'],
    };
}

export function FeedbackUpdateDTOToJSON(value?: FeedbackUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'feedbackId': value.feedbackId,
        'rating': value.rating,
        'frequentedSection': value.frequentedSection,
        'suggestion': value.suggestion,
        'responseWanted': value.responseWanted,
    };
}

