/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface FeedbackDTO
 */
export interface FeedbackDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackDTO
     */
    feedbackId?: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackDTO
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDTO
     */
    frequentedSection?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDTO
     */
    suggestion?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FeedbackDTO
     */
    responseWanted?: number;
    /**
     * 
     * @type {UserDTO}
     * @memberof FeedbackDTO
     */
    givenBy?: UserDTO;
}

/**
 * Check if a given object implements the FeedbackDTO interface.
 */
export function instanceOfFeedbackDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackDTOFromJSON(json: any): FeedbackDTO {
    return FeedbackDTOFromJSONTyped(json, false);
}

export function FeedbackDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'feedbackId': !exists(json, 'feedbackId') ? undefined : json['feedbackId'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'frequentedSection': !exists(json, 'frequentedSection') ? undefined : json['frequentedSection'],
        'suggestion': !exists(json, 'suggestion') ? undefined : json['suggestion'],
        'responseWanted': !exists(json, 'responseWanted') ? undefined : json['responseWanted'],
        'givenBy': !exists(json, 'givenBy') ? undefined : UserDTOFromJSON(json['givenBy']),
    };
}

export function FeedbackDTOToJSON(value?: FeedbackDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'feedbackId': value.feedbackId,
        'rating': value.rating,
        'frequentedSection': value.frequentedSection,
        'suggestion': value.suggestion,
        'responseWanted': value.responseWanted,
        'givenBy': UserDTOToJSON(value.givenBy),
    };
}

