/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface MemberDTO
 */
export interface MemberDTO {
    /**
     * 
     * @type {string}
     * @memberof MemberDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MemberDTO
     */
    email?: string | null;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof MemberDTO
     */
    role?: UserRoleEnum;
}

/**
 * Check if a given object implements the MemberDTO interface.
 */
export function instanceOfMemberDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MemberDTOFromJSON(json: any): MemberDTO {
    return MemberDTOFromJSONTyped(json, false);
}

export function MemberDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'role': !exists(json, 'role') ? undefined : UserRoleEnumFromJSON(json['role']),
    };
}

export function MemberDTOToJSON(value?: MemberDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'role': UserRoleEnumToJSON(value.role),
    };
}

