/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MembersDTO
 */
export interface MembersDTO {
    /**
     * 
     * @type {Array<string>}
     * @memberof MembersDTO
     */
    email?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof MembersDTO
     */
    teamName?: string | null;
}

/**
 * Check if a given object implements the MembersDTO interface.
 */
export function instanceOfMembersDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MembersDTOFromJSON(json: any): MembersDTO {
    return MembersDTOFromJSONTyped(json, false);
}

export function MembersDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembersDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'teamName': !exists(json, 'teamName') ? undefined : json['teamName'],
    };
}

export function MembersDTOToJSON(value?: MembersDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'teamName': value.teamName,
    };
}

