/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectAddDTO
 */
export interface ProjectAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ProjectAddDTO
     */
    projectName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectAddDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ProjectAddDTO interface.
 */
export function instanceOfProjectAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectAddDTOFromJSON(json: any): ProjectAddDTO {
    return ProjectAddDTOFromJSONTyped(json, false);
}

export function ProjectAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'projectName': !exists(json, 'projectName') ? undefined : json['projectName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ProjectAddDTOToJSON(value?: ProjectAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'projectName': value.projectName,
        'description': value.description,
    };
}

