/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { ProjectDTO } from './ProjectDTO';
import {
    ProjectDTOFromJSON,
    ProjectDTOFromJSONTyped,
    ProjectDTOToJSON,
} from './ProjectDTO';

/**
 * 
 * @export
 * @interface ProjectDTORequestResponse
 */
export interface ProjectDTORequestResponse {
    /**
     * 
     * @type {ProjectDTO}
     * @memberof ProjectDTORequestResponse
     */
    response?: ProjectDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ProjectDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ProjectDTORequestResponse interface.
 */
export function instanceOfProjectDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectDTORequestResponseFromJSON(json: any): ProjectDTORequestResponse {
    return ProjectDTORequestResponseFromJSONTyped(json, false);
}

export function ProjectDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ProjectDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ProjectDTORequestResponseToJSON(value?: ProjectDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ProjectDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

