/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { ProjectDTOPagedResponse } from './ProjectDTOPagedResponse';
import {
    ProjectDTOPagedResponseFromJSON,
    ProjectDTOPagedResponseFromJSONTyped,
    ProjectDTOPagedResponseToJSON,
} from './ProjectDTOPagedResponse';

/**
 * 
 * @export
 * @interface ProjectDTOPagedResponseRequestResponse
 */
export interface ProjectDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ProjectDTOPagedResponse}
     * @memberof ProjectDTOPagedResponseRequestResponse
     */
    response?: ProjectDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ProjectDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ProjectDTOPagedResponseRequestResponse interface.
 */
export function instanceOfProjectDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectDTOPagedResponseRequestResponseFromJSON(json: any): ProjectDTOPagedResponseRequestResponse {
    return ProjectDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ProjectDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ProjectDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ProjectDTOPagedResponseRequestResponseToJSON(value?: ProjectDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ProjectDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

