/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectUpdateDTO
 */
export interface ProjectUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDTO
     */
    projectId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDTO
     */
    projectName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ProjectUpdateDTO interface.
 */
export function instanceOfProjectUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectUpdateDTOFromJSON(json: any): ProjectUpdateDTO {
    return ProjectUpdateDTOFromJSONTyped(json, false);
}

export function ProjectUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'projectId': !exists(json, 'projectId') ? undefined : json['projectId'],
        'projectName': !exists(json, 'projectName') ? undefined : json['projectName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ProjectUpdateDTOToJSON(value?: ProjectUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'projectId': value.projectId,
        'projectName': value.projectName,
        'description': value.description,
    };
}

