/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectMembersDTO
 */
export interface ProjectMembersDTO {
    /**
     * 
     * @type {string}
     * @memberof ProjectMembersDTO
     */
    projectId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectMembersDTO
     */
    userIds?: Array<string> | null;
}

/**
 * Check if a given object implements the ProjectMembersDTO interface.
 */
export function instanceOfProjectMembersDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectMembersDTOFromJSON(json: any): ProjectMembersDTO {
    return ProjectMembersDTOFromJSONTyped(json, false);
}

export function ProjectMembersDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectMembersDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'projectId': !exists(json, 'projectId') ? undefined : json['projectId'],
        'userIds': !exists(json, 'userIds') ? undefined : json['userIds'],
    };
}

export function ProjectMembersDTOToJSON(value?: ProjectMembersDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'projectId': value.projectId,
        'userIds': value.userIds,
    };
}

