/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TaskStatusEnum } from './TaskStatusEnum';
import {
    TaskStatusEnumFromJSON,
    TaskStatusEnumFromJSONTyped,
    TaskStatusEnumToJSON,
} from './TaskStatusEnum';

/**
 * 
 * @export
 * @interface ProjectTaskUpdateDTO
 */
export interface ProjectTaskUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ProjectTaskUpdateDTO
     */
    taskId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectTaskUpdateDTO
     */
    taskName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectTaskUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {TaskStatusEnum}
     * @memberof ProjectTaskUpdateDTO
     */
    status?: TaskStatusEnum;
}

/**
 * Check if a given object implements the ProjectTaskUpdateDTO interface.
 */
export function instanceOfProjectTaskUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectTaskUpdateDTOFromJSON(json: any): ProjectTaskUpdateDTO {
    return ProjectTaskUpdateDTOFromJSONTyped(json, false);
}

export function ProjectTaskUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectTaskUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': !exists(json, 'taskId') ? undefined : json['taskId'],
        'taskName': !exists(json, 'taskName') ? undefined : json['taskName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'status': !exists(json, 'status') ? undefined : TaskStatusEnumFromJSON(json['status']),
    };
}

export function ProjectTaskUpdateDTOToJSON(value?: ProjectTaskUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'taskId': value.taskId,
        'taskName': value.taskName,
        'description': value.description,
        'status': TaskStatusEnumToJSON(value.status),
    };
}

