/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { ProjectTaskDTO } from './ProjectTaskDTO';
import {
    ProjectTaskDTOFromJSON,
    ProjectTaskDTOFromJSONTyped,
    ProjectTaskDTOToJSON,
} from './ProjectTaskDTO';

/**
 * 
 * @export
 * @interface ProjectTaskDTORequestResponse
 */
export interface ProjectTaskDTORequestResponse {
    /**
     * 
     * @type {ProjectTaskDTO}
     * @memberof ProjectTaskDTORequestResponse
     */
    response?: ProjectTaskDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ProjectTaskDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ProjectTaskDTORequestResponse interface.
 */
export function instanceOfProjectTaskDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectTaskDTORequestResponseFromJSON(json: any): ProjectTaskDTORequestResponse {
    return ProjectTaskDTORequestResponseFromJSONTyped(json, false);
}

export function ProjectTaskDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectTaskDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ProjectTaskDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ProjectTaskDTORequestResponseToJSON(value?: ProjectTaskDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ProjectTaskDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

