/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { QuestionDTOPagedResponse } from './QuestionDTOPagedResponse';
import {
    QuestionDTOPagedResponseFromJSON,
    QuestionDTOPagedResponseFromJSONTyped,
    QuestionDTOPagedResponseToJSON,
} from './QuestionDTOPagedResponse';

/**
 * 
 * @export
 * @interface QuestionDTOPagedResponseRequestResponse
 */
export interface QuestionDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {QuestionDTOPagedResponse}
     * @memberof QuestionDTOPagedResponseRequestResponse
     */
    response?: QuestionDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof QuestionDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the QuestionDTOPagedResponseRequestResponse interface.
 */
export function instanceOfQuestionDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QuestionDTOPagedResponseRequestResponseFromJSON(json: any): QuestionDTOPagedResponseRequestResponse {
    return QuestionDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function QuestionDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : QuestionDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function QuestionDTOPagedResponseRequestResponseToJSON(value?: QuestionDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': QuestionDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

