/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { QuestionDTO } from './QuestionDTO';
import {
    QuestionDTOFromJSON,
    QuestionDTOFromJSONTyped,
    QuestionDTOToJSON,
} from './QuestionDTO';

/**
 * 
 * @export
 * @interface QuestionDTORequestResponse
 */
export interface QuestionDTORequestResponse {
    /**
     * 
     * @type {QuestionDTO}
     * @memberof QuestionDTORequestResponse
     */
    response?: QuestionDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof QuestionDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the QuestionDTORequestResponse interface.
 */
export function instanceOfQuestionDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QuestionDTORequestResponseFromJSON(json: any): QuestionDTORequestResponse {
    return QuestionDTORequestResponseFromJSONTyped(json, false);
}

export function QuestionDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : QuestionDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function QuestionDTORequestResponseToJSON(value?: QuestionDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': QuestionDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

