/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionUpdateDTO
 */
export interface QuestionUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof QuestionUpdateDTO
     */
    questionId?: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionUpdateDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof QuestionUpdateDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the QuestionUpdateDTO interface.
 */
export function instanceOfQuestionUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QuestionUpdateDTOFromJSON(json: any): QuestionUpdateDTO {
    return QuestionUpdateDTOFromJSONTyped(json, false);
}

export function QuestionUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'questionId': !exists(json, 'questionId') ? undefined : json['questionId'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function QuestionUpdateDTOToJSON(value?: QuestionUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'questionId': value.questionId,
        'title': value.title,
        'description': value.description,
    };
}

