/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TaskStatusEnum } from './TaskStatusEnum';
import {
    TaskStatusEnumFromJSON,
    TaskStatusEnumFromJSONTyped,
    TaskStatusEnumToJSON,
} from './TaskStatusEnum';

/**
 * 
 * @export
 * @interface TaskGetDTO
 */
export interface TaskGetDTO {
    /**
     * 
     * @type {string}
     * @memberof TaskGetDTO
     */
    taskName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskGetDTO
     */
    description?: string | null;
    /**
     * 
     * @type {TaskStatusEnum}
     * @memberof TaskGetDTO
     */
    status?: TaskStatusEnum;
}

/**
 * Check if a given object implements the TaskGetDTO interface.
 */
export function instanceOfTaskGetDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TaskGetDTOFromJSON(json: any): TaskGetDTO {
    return TaskGetDTOFromJSONTyped(json, false);
}

export function TaskGetDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskGetDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskName': !exists(json, 'taskName') ? undefined : json['taskName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'status': !exists(json, 'status') ? undefined : TaskStatusEnumFromJSON(json['status']),
    };
}

export function TaskGetDTOToJSON(value?: TaskGetDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'taskName': value.taskName,
        'description': value.description,
        'status': TaskStatusEnumToJSON(value.status),
    };
}

