/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TaskGetDTO } from './TaskGetDTO';
import {
    TaskGetDTOFromJSON,
    TaskGetDTOFromJSONTyped,
    TaskGetDTOToJSON,
} from './TaskGetDTO';

/**
 * 
 * @export
 * @interface TaskGetDTOListRequestResponse
 */
export interface TaskGetDTOListRequestResponse {
    /**
     * 
     * @type {Array<TaskGetDTO>}
     * @memberof TaskGetDTOListRequestResponse
     */
    readonly response?: Array<TaskGetDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TaskGetDTOListRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TaskGetDTOListRequestResponse interface.
 */
export function instanceOfTaskGetDTOListRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TaskGetDTOListRequestResponseFromJSON(json: any): TaskGetDTOListRequestResponse {
    return TaskGetDTOListRequestResponseFromJSONTyped(json, false);
}

export function TaskGetDTOListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskGetDTOListRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : (json['response'] === null ? null : (json['response'] as Array<any>).map(TaskGetDTOFromJSON)),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TaskGetDTOListRequestResponseToJSON(value?: TaskGetDTOListRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

