/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TaskStatusEnum = {
    Open: 'Open',
    InProgress: 'InProgress',
    Review: 'Review',
    Done: 'Done'
} as const;
export type TaskStatusEnum = typeof TaskStatusEnum[keyof typeof TaskStatusEnum];


export function TaskStatusEnumFromJSON(json: any): TaskStatusEnum {
    return TaskStatusEnumFromJSONTyped(json, false);
}

export function TaskStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskStatusEnum {
    return json as TaskStatusEnum;
}

export function TaskStatusEnumToJSON(value?: TaskStatusEnum | null): any {
    return value as any;
}

