/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TeamDTO } from './TeamDTO';
import {
    TeamDTOFromJSON,
    TeamDTOFromJSONTyped,
    TeamDTOToJSON,
} from './TeamDTO';

/**
 * 
 * @export
 * @interface TeamDTOPagedResponse
 */
export interface TeamDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof TeamDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<TeamDTO>}
     * @memberof TeamDTOPagedResponse
     */
    data?: Array<TeamDTO> | null;
}

/**
 * Check if a given object implements the TeamDTOPagedResponse interface.
 */
export function instanceOfTeamDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamDTOPagedResponseFromJSON(json: any): TeamDTOPagedResponse {
    return TeamDTOPagedResponseFromJSONTyped(json, false);
}

export function TeamDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(TeamDTOFromJSON)),
    };
}

export function TeamDTOPagedResponseToJSON(value?: TeamDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(TeamDTOToJSON)),
    };
}

