/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamUpdateDTO
 */
export interface TeamUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof TeamUpdateDTO
     */
    teamId?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamUpdateDTO
     */
    teamName?: string | null;
}

/**
 * Check if a given object implements the TeamUpdateDTO interface.
 */
export function instanceOfTeamUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamUpdateDTOFromJSON(json: any): TeamUpdateDTO {
    return TeamUpdateDTOFromJSONTyped(json, false);
}

export function TeamUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teamId': !exists(json, 'teamId') ? undefined : json['teamId'],
        'teamName': !exists(json, 'teamName') ? undefined : json['teamName'],
    };
}

export function TeamUpdateDTOToJSON(value?: TeamUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'teamId': value.teamId,
        'teamName': value.teamName,
    };
}

