/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamAddDTO
 */
export interface TeamAddDTO {
    /**
     * 
     * @type {string}
     * @memberof TeamAddDTO
     */
    teamName?: string | null;
}

/**
 * Check if a given object implements the TeamAddDTO interface.
 */
export function instanceOfTeamAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamAddDTOFromJSON(json: any): TeamAddDTO {
    return TeamAddDTOFromJSONTyped(json, false);
}

export function TeamAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teamName': !exists(json, 'teamName') ? undefined : json['teamName'],
    };
}

export function TeamAddDTOToJSON(value?: TeamAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'teamName': value.teamName,
    };
}

