/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TeamDTOPagedResponse } from './TeamDTOPagedResponse';
import {
    TeamDTOPagedResponseFromJSON,
    TeamDTOPagedResponseFromJSONTyped,
    TeamDTOPagedResponseToJSON,
} from './TeamDTOPagedResponse';

/**
 * 
 * @export
 * @interface TeamDTOPagedResponseRequestResponse
 */
export interface TeamDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {TeamDTOPagedResponse}
     * @memberof TeamDTOPagedResponseRequestResponse
     */
    response?: TeamDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TeamDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TeamDTOPagedResponseRequestResponse interface.
 */
export function instanceOfTeamDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamDTOPagedResponseRequestResponseFromJSON(json: any): TeamDTOPagedResponseRequestResponse {
    return TeamDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function TeamDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : TeamDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TeamDTOPagedResponseRequestResponseToJSON(value?: TeamDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': TeamDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

