/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface TeamDTO
 */
export interface TeamDTO {
    /**
     * 
     * @type {string}
     * @memberof TeamDTO
     */
    teamId?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamDTO
     */
    teamName?: string | null;
    /**
     * 
     * @type {UserDTO}
     * @memberof TeamDTO
     */
    teamLeader?: UserDTO;
}

/**
 * Check if a given object implements the TeamDTO interface.
 */
export function instanceOfTeamDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamDTOFromJSON(json: any): TeamDTO {
    return TeamDTOFromJSONTyped(json, false);
}

export function TeamDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teamId': !exists(json, 'teamId') ? undefined : json['teamId'],
        'teamName': !exists(json, 'teamName') ? undefined : json['teamName'],
        'teamLeader': !exists(json, 'teamLeader') ? undefined : UserDTOFromJSON(json['teamLeader']),
    };
}

export function TeamDTOToJSON(value?: TeamDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'teamId': value.teamId,
        'teamName': value.teamName,
        'teamLeader': UserDTOToJSON(value.teamLeader),
    };
}

