/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TeamDTO } from './TeamDTO';
import {
    TeamDTOFromJSON,
    TeamDTOFromJSONTyped,
    TeamDTOToJSON,
} from './TeamDTO';

/**
 * 
 * @export
 * @interface TeamDTORequestResponse
 */
export interface TeamDTORequestResponse {
    /**
     * 
     * @type {TeamDTO}
     * @memberof TeamDTORequestResponse
     */
    response?: TeamDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TeamDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TeamDTORequestResponse interface.
 */
export function instanceOfTeamDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamDTORequestResponseFromJSON(json: any): TeamDTORequestResponse {
    return TeamDTORequestResponseFromJSONTyped(json, false);
}

export function TeamDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : TeamDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TeamDTORequestResponseToJSON(value?: TeamDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': TeamDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

