/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface UserGetDTO
 */
export interface UserGetDTO {
    /**
     * 
     * @type {string}
     * @memberof UserGetDTO
     */
    name?: string | null;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof UserGetDTO
     */
    role?: UserRoleEnum;
}

/**
 * Check if a given object implements the UserGetDTO interface.
 */
export function instanceOfUserGetDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserGetDTOFromJSON(json: any): UserGetDTO {
    return UserGetDTOFromJSONTyped(json, false);
}

export function UserGetDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGetDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'role': !exists(json, 'role') ? undefined : UserRoleEnumFromJSON(json['role']),
    };
}

export function UserGetDTOToJSON(value?: UserGetDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'role': UserRoleEnumToJSON(value.role),
    };
}

